[package]
name = "wasm_hashing"
version = "0.1.0"
authors = ["Chris Adams <cadams@loc.gov>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
sha1 = "0.6.0"
sha2 = "0.7.1"
sha3 = "0.7.3"
wasm-bindgen = "0.2.11"
