[package]
name = "wasm_hashing"
version = "0.1.0"
authors = ["Chris Adams <cadams@loc.gov>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
hex = "0.3.2"
digest = "0.7.5"
sha-1 = "0.7.0"
sha2 = "0.7.1"
sha3 = "0.7.3"
wasm-bindgen = "0.2.15"
